In [1]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
from sklearn.decomposition import PCA

import numpy as np
import pandas as pd

import matplotlib as plt
from sklearn.cluster import DBSCAN
from sklearn import metrics
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

import nltk
import seaborn as sns
from nltk.corpus import stopwords

C:\Users\Alex\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Alex\anaconda3\lib\site-packages\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran-win_amd64.dll
C:\Users\Alex\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
df=pd.read_csv('Новая выгрузка обр.csv', encoding="cp1251")
df

Автор                                Место работы автора  \
0         Антонова С.В.                                     АО «Интерфакс»   
1        Картошкин С.А.      Министерство просвещения Российской Федерации   
2          Цивилев С.Е.                  Администрация Кемеровской области   
3           Волков Г.А.       Министерство транспорта Российской Федерации   
4           Атанов И.В.  Ставропольский государственный аграрный универ...   
...                 ...                                                ...   
4887    Запруднова Е.В.                 Администрация Владимирской области   
4888  Черноскутова И.А.  Министерство образования и науки Российской Фе...   
4889      Медведев Д.А.         Аппарат Правительства Российской Федерации   
4890      Синюгина Т.Ю.  Министерство образования и науки РФ. Заместите...   
4891         Асаул Н.А.       Министерство транспорта Российской Федерации   

          Адресат     Специализация адресата  \
0     Уразов Р.Н.       Генеральный директор   
1     Уразов Р.Н.       Генеральный директор   
2     Уразов Р.Н.       Генеральный директор   
3     Иванюк Л.А.  Административный директор   
4     Уразов Р.Н.       Генеральный директор   
...           ...                        ...   
4887  Уразов Р.Н.       Генеральный директор   
4888  Уразов Р.Н.       Генеральный директор   
4889  Уразов Р.Н.       Генеральный директор   
4890  Уразов Р.Н.       Генеральный директор   
4891  Уразов Р.Н.       Генеральный директор   

                                             Содержание  \
0     возможн использован сетев издан информацион ре...   
1     участ совещан вопрос доработк фэ предоставлен ...   
2     командирован саликов к. глушк д. участ заседан...   
3     участ чемпионат мир профессиональн мастерств с...   
4     участ церемон открыт вузовск чемпионат 15 апр ...   
...                                                 ...   
4887  присутств школьник миров чемпионат казан предп...   
4888  заседан рабоч групп приоритетн проект рабоч ка...   
4889  протокол заседан президиум совет президент рф ...   
4890  проведен 21.11.2017 заседан организацион комит...   
4891  участ чемпионат WorldSkills Hi-Tech екатеринбу...   

                                Примечание  
0                                           
1                                           
2                                           
3                                           
4                                           
...                                    ...  
4887  переда митькин а. т.к. ответ е письм  
4888                                        
4889                                        
4890                                        
4891                                        

[4892 rows x 6 columns]

In [3]:
X = df['Содержание']
y = df["Специализация адресата"]

In [4]:
X

0       возможн использован сетев издан информацион ре...
1       участ совещан вопрос доработк фэ предоставлен ...
2       командирован саликов к. глушк д. участ заседан...
3       участ чемпионат мир профессиональн мастерств с...
4       участ церемон открыт вузовск чемпионат 15 апр ...
                              ...                        
4887    присутств школьник миров чемпионат казан предп...
4888    заседан рабоч групп приоритетн проект рабоч ка...
4889    протокол заседан президиум совет президент рф ...
4890    проведен 21.11.2017 заседан организацион комит...
4891    участ чемпионат WorldSkills Hi-Tech екатеринбу...
Name: Содержание, Length: 4892, dtype: object

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words=stopwords.words('russian'))
X = vectorizer.fit_transform(X).toarray()

In [6]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfconverter = TfidfTransformer()
X = tfidfconverter.fit_transform(X).toarray()

In [165]:
feature_weight = X.sum(axis=0).tolist()[0]
features = pd.DataFrame(feature_weight)
features.index =  list(vectorizer.get_feature_names())
features.sort_values(by=[0],ascending=False).head(20).plot.barh(figsize=(20,10),color = 'green')

ValueError: DataFrame constructor not properly called!

In [166]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [176]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [167]:
y_test

751                       Генеральный директор
3315                 Административный директор
1220                 Административный директор
1362            Вопросы повышения квалификации
4482                              Поздравления
                         ...                  
2782                      Генеральный директор
446                  Сертификация экспертов WS
1176                      Генеральный директор
4599    Специалист по региональным чемпионатам
4665    Специалист по региональным чемпионатам
Name: Специализация адресата, Length: 979, dtype: object

In [168]:
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
nltk.download('stopwords')
import pickle
from nltk.corpus import stopwords
from sklearn.ensemble import RandomForestClassifier

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Alex\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [169]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [170]:
classifier = RandomForestClassifier(n_estimators=1000, random_state=0)
classifier.fit(X_train, y_train)


RandomForestClassifier(n_estimators=1000, random_state=0)

In [171]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [172]:
y_pred = classifier.predict(X_test)


In [173]:
y_pred

array(['Генеральный директор', 'Административный директор',
       'Административный директор', 'Генеральный директор',
       'Поздравления', 'Генеральный директор', 'Генеральный директор',
       'Вузовские чемпионаты', 'Генеральный директор',
       'Вопросы повышения квалификации',
       'Специалист по региональным чемпионатам', 'Генеральный директор',
       'Специалист по региональным чемпионатам',
       'Административный директор', 'Вопросы повышения квалификации',
       'Генеральный директор', 'Административный директор',
       'Специалист по региональным чемпионатам',
       'Административный директор', 'Вузовские чемпионаты',
       'Генеральный директор', 'Генеральный директор',
       'Административный директор',
       'Специалист по региональным чемпионатам', 'Генеральный директор',
       'Специалист по региональным чемпионатам',
       'Специалист по региональным чемпионатам',
       'Специалист по региональным чемпионатам',
       'Специалист по региональным чемпио

In [174]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))


[[  0   0   0   0   0   2   0   0   0   0   0   0]
 [  0  79   0   4   1  28   0   1   0   5  21   0]
 [  0   0  13   0   1   2   0   0   0   4   3   0]
 [  0   6   0  35   0  16   1   0   0   1   3   0]
 [  0   1   1   0  42   1   0   0   0   1   3   0]
 [  0  17   1   5   2 232   1   0   0   1  32   0]
 [  0   4   0   0   0  10  14   0   0   1   5   0]
 [  0   1   0   0   0   6   1   9   0   0   0   0]
 [  0   1   0   1   0   5   0   0   2   0   1   0]
 [  0   5   1   0   3  10   0   0   0   7   6   0]
 [  0  15   0   1   1  27   0   1   0   3 268   0]
 [  0   0   0   1   0   1   0   0   0   0   2   0]]
                                        precision    recall  f1-score   support

                             WS Europe       0.00      0.00      0.00         2
             Административный директор       0.61      0.57      0.59       139
                  Вопросы аккредитации       0.81      0.57      0.67        23
        Вопросы повышения квалификации       0.74      0.56      0

C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [175]:
filename = 'MODEL.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [181]:
import nltk
import numpy as np
import random
import string # to process standard python strings
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import datasets
from sklearn.decomposition import PCA

import numpy as np
import pandas as pd

import matplotlib as plt
from sklearn.cluster import DBSCAN
from sklearn import metrics
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from sklearn.feature_extraction.text import CountVectorizer
import pickle
from sklearn.feature_extraction.text import TfidfTransformer

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Alex\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Alex\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Alex\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [190]:
stopwords = nltk.corpus.stopwords.words('russian')
stopwords.append('вх')
stopwords.append('об')
stopwords.append('-')
stopwords.append('"')
stopwords.append('``')
stopwords.append(',')
stopwords.append('.')
stopwords.append('»')
stopwords.append('«')
stopwords.append('(')
stopwords.append('\'\'')
stopwords.append(')')
content=[]
text = input("Введите краткое содержание вашего письма")
text = pd.Series(text)
for i in text:
    content.append(word_tokenize(i, language="russian"))
new_content=content
snowball = SnowballStemmer(language="russian")
for x in range(0,len(new_content)):
    for y in range(0,len(new_content[x])):
        ss = new_content[x][y]
    new_content[x][y]=snowball.stem(ss)
stop_words = stopwords
filtered_str=[]
new_content2=[]
for x in range(0,len(new_content)):
    for y in range(0,len(new_content[x])):
        filtered_str=' '.join((filter(lambda s: s not in stop_words,new_content[x])))
    new_content2.append(filtered_str)
        
content = pd.Series(new_content2)
content

Введите краткое содержание вашего письмакраткое содержание вашего письма


0    краткое содержание вашего письм
dtype: object

In [178]:
loaded_model = pickle.load(open('MODEL.sav', 'rb'))
y_pred = loaded_model.predict(X_test)
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [103]:
from sklearn.linear_model import LogisticRegression

In [109]:
model = LogisticRegression(random_state=1)
model.fit(X_train, y_train)
print(confusion_matrix(y_test,model.predict(X_test)))
print(classification_report(y_test,model.predict(X_test)))
print(accuracy_score(y_test, model.predict(X_test)))

[[  0   0   0   0   0   1   0   0   0   0   1   0]
 [  0  65   0   4   2  44   1   0   0   2  21   0]
 [  0   1   9   0   1   5   0   0   0   4   3   0]
 [  0   4   0  33   0  18   0   0   0   3   4   0]
 [  0   2   0   0  37   6   0   0   0   1   3   0]
 [  0  13   0   3   0 230   0   0   0   1  44   0]
 [  0   6   0   1   0  10  11   1   0   1   4   0]
 [  0   1   0   0   0   4   2   9   0   0   1   0]
 [  0   1   0   1   0   5   0   0   2   0   1   0]
 [  0   5   0   0   4  11   1   0   0   5   6   0]
 [  0   7   1   0   1  29   0   1   0   1 276   0]
 [  0   1   0   0   0   1   0   0   0   0   2   0]]
                                        precision    recall  f1-score   support

                             WS Europe       0.00      0.00      0.00         2
             Административный директор       0.61      0.47      0.53       139
                  Вопросы аккредитации       0.90      0.39      0.55        23
        Вопросы повышения квалификации       0.79      0.53      0

C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [147]:
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(max_depth=4, random_state=42)
tree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [148]:
y_pred_tree = tree.predict(X_test)
print(confusion_matrix(y_test,tree.predict(X_test)))
print(classification_report(y_test,tree.predict(X_test)))
print(accuracy_score(y_test, tree.predict(X_test)))

[[  0   0   0   0   0   2   0   0   0   0   0   0]
 [  0   1   0   0   0 100   0   0   0   0  38   0]
 [  0   0   0   0   0  22   0   0   0   0   1   0]
 [  0   0   0  20   0  38   0   0   0   0   4   0]
 [  0   0   0   0  22  17   0   0   0   0  10   0]
 [  0   0   0   0   1 236   0   1   0   0  53   0]
 [  0   0   0   0   0  16   0   0   0   0  18   0]
 [  0   0   0   0   0   6   0   3   0   0   8   0]
 [  0   0   0   0   0   9   0   0   0   0   1   0]
 [  0   0   0   0   2  22   0   0   0   0   8   0]
 [  0   0   0   0   0 172   0   1   0   0 143   0]
 [  0   0   0   0   0   4   0   0   0   0   0   0]]
                                        precision    recall  f1-score   support

                             WS Europe       0.00      0.00      0.00         2
             Административный директор       1.00      0.01      0.01       139
                  Вопросы аккредитации       0.00      0.00      0.00        23
        Вопросы повышения квалификации       1.00      0.32      0

C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [149]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, p=2)
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)
print(confusion_matrix(y_test,knn.predict(X_test)))
print(classification_report(y_test,knn.predict(X_test)))
print(accuracy_score(y_test, knn.predict(X_test)))

[[  1   1   0   0   0   0   0   0   0   0   0   0]
 [  0 104   1   6   2   9   1   1   0   1  14   0]
 [  1   5  10   0   1   2   0   0   0   2   2   0]
 [  0  23   0  33   1   4   0   0   0   1   0   0]
 [  0  12   1   0  32   1   1   0   0   1   1   0]
 [  0 142   0   4   2 114   3   1   0   4  21   0]
 [  0  13   0   1   0   2  16   1   0   1   0   0]
 [  0   2   0   0   0   3   0  12   0   0   0   0]
 [  1   4   0   1   1   1   0   0   2   0   0   0]
 [  0  21   0   0   2   3   1   0   0   4   1   0]
 [  0  55   2   1   1   9   1   2   0   1 244   0]
 [  0   4   0   0   0   0   0   0   0   0   0   0]]
                                        precision    recall  f1-score   support

                             WS Europe       0.33      0.50      0.40         2
             Административный директор       0.27      0.75      0.40       139
                  Вопросы аккредитации       0.71      0.43      0.54        23
        Вопросы повышения квалификации       0.72      0.53      0

C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [150]:
from sklearn.svm import SVC

svm = SVC(kernel='linear', C=1.0, random_state=1)
svm.fit(X_train, y_train)

SVC(kernel='linear', random_state=1)

In [151]:
y_pred_svm = svm.predict(X_test)

In [153]:
print(confusion_matrix(y_test,svm.predict(X_test)))
print(classification_report(y_test,svm.predict(X_test)))
print(accuracy_score(y_test, svm.predict(X_test)))

[[  0   0   0   0   0   2   0   0   0   0   0   0]
 [  0  68   0   6   3  38   0   0   0   6  18   0]
 [  0   2  10   0   1   4   0   0   0   3   3   0]
 [  0   6   0  35   0  13   0   0   0   3   5   0]
 [  0   2   0   0  43   1   0   0   0   1   2   0]
 [  1  14   0   4   1 223   1   1   0   3  43   0]
 [  0   4   0   1   0   9  16   1   0   2   1   0]
 [  0   4   0   0   0   3   0  10   0   0   0   0]
 [  0   2   0   1   0   4   0   0   2   0   1   0]
 [  0   4   0   0   3   9   1   0   0  11   4   0]
 [  0   7   1   1   1  28   0   1   0   3 274   0]
 [  0   1   0   0   0   1   0   0   0   0   2   0]]
                                        precision    recall  f1-score   support

                             WS Europe       0.00      0.00      0.00         2
             Административный директор       0.60      0.49      0.54       139
                  Вопросы аккредитации       0.91      0.43      0.59        23
        Вопросы повышения квалификации       0.73      0.56      0

C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Alex\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
